### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by Ryyn-Sd** [issuekit/action#3]
This doesn't work for me

**Comment by nthnchu** [comment]
Hey @Ryyn-Sd! Sorry this doesn't work for you. What repository is this broken on? Please provide all information that might be helpful in solving this bug.

**Comment by Ryyn-Sd** [comment]
It's broken on [This repository](https://github.com/rayyansaidi-com/app)

**Comment by nthnchu** [comment]
Ok, thank you for the link. Are you experiencing this issue anywhere else?

**Comment by Ryyn-Sd** [comment]
I never tried

**Comment by Ryyn-Sd** [comment]
I'll try it.

**Comment by nthnchu** [comment]
I have fixed this (bbf3f4b4b58438f5ddaadf662c01f0e5fa830a4f). Please open another issue if you are still experiencing this problem
